# Generated by Django 5.2.1 on 2026-08-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctx_work', '0008_document_version_operations'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='operational_data',
            field=models.JSONField(blank=True, default=dict, help_text='Service-specific operational values captured for this work item.'),
        ),
    ]
