# Generated by Django 5.2.1 on 2026-08-11 08:31

import core.db.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctx_work', '0009_workitem_operational_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkProcessState',
            fields=[
                ('id', models.UUIDField(default=core.db.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.UUIDField()),
                ('row_version', models.PositiveIntegerField(default=0)),
                ('work_item_id', models.UUIDField(db_index=True)),
                ('current_step_id', models.UUIDField(db_index=True)),
                ('entered_at', models.DateTimeField()),
                ('entered_by', models.UUIDField()),
                ('note', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ('-entered_at', 'work_item_id', 'id'),
                'indexes': [models.Index(fields=['tenant_id', 'current_step_id'], name='wrk_procstate_step_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'work_item_id'), name='uniq_work_process_state_work')],
            },
        ),
    ]
