# Generated by Django 5.2.1 on 2026-08-06 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctx_authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessprofile',
            options={'ordering': ['tenant_id', 'user_account_id']},
        ),
        migrations.AlterUniqueTogether(
            name='roleaccess',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='access',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='access',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='accessprofile',
            name='additional_access',
            field=models.ManyToManyField(blank=True, related_name='additional_profiles', to='ctx_authorization.access'),
        ),
        migrations.AddField(
            model_name='accessprofile',
            name='department_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='accessprofile',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='accessprofile',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_profiles', to='ctx_authorization.roletemplate'),
        ),
        migrations.AddField(
            model_name='accessprofile',
            name='service_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='accessprofile',
            name='team_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='accessprofile',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='accessprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='accessprofile',
            name='user_account_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='roleaccess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Blank for Vridhi system templates.', null=True),
        ),
        migrations.AlterField(
            model_name='access',
            name='module',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='roletemplate',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='roletemplate',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='roletemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='accessprofile',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'user_account_id'), name='uq_auth_profile_tenant_user'),
        ),
        migrations.AddConstraint(
            model_name='roleaccess',
            constraint=models.UniqueConstraint(fields=('role', 'access'), name='uq_auth_role_access'),
        ),
        migrations.AddConstraint(
            model_name='roletemplate',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'code'), name='uq_auth_role_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='roletemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant_id__isnull', True)), fields=('code',), name='uq_auth_system_role_code'),
        ),
    ]
