# Generated by Django 5.2.1 on 2026-07-28 04:52

import core.db.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBranch',
            fields=[
                ('id', models.UUIDField(default=core.db.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.UUIDField()),
                ('row_version', models.PositiveIntegerField(default=0)),
                ('client_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=160)),
                ('address', models.TextField(blank=True)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('contact_name', models.CharField(blank=True, max_length=180)),
                ('contact_mobile', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.UUIDField(default=core.db.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.UUIDField()),
                ('row_version', models.PositiveIntegerField(default=0)),
                ('client_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=180)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=core.db.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.UUIDField()),
                ('row_version', models.PositiveIntegerField(default=0)),
                ('legal_name', models.CharField(max_length=250)),
                ('trade_name', models.CharField(blank=True, max_length=250)),
                ('client_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('PROPRIETORSHIP', 'Proprietorship'), ('PARTNERSHIP', 'Partnership'), ('LLP', 'LLP'), ('PRIVATE_LIMITED', 'Private Limited Company'), ('PUBLIC_LIMITED', 'Public Limited Company'), ('TRUST', 'Trust'), ('OTHER', 'Other')], max_length=25)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('pan', models.CharField(blank=True, max_length=10)),
                ('cin_or_llpin', models.CharField(blank=True, max_length=30)),
                ('registered_address', models.TextField(blank=True)),
                ('relationship_manager_id', models.UUIDField(blank=True, null=True)),
                ('engagement_status', models.CharField(choices=[('ACTIVE', 'Active'), ('PROSPECT', 'Prospect'), ('ON_HOLD', 'On hold'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=15)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['legal_name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('pan', ''), _negated=True), fields=('tenant_id', 'pan'), name='uq_client_pan_tenant')],
            },
        ),
        migrations.CreateModel(
            name='ClientGSTRegistration',
            fields=[
                ('id', models.UUIDField(default=core.db.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.UUIDField()),
                ('row_version', models.PositiveIntegerField(default=0)),
                ('client_id', models.UUIDField(db_index=True)),
                ('gstin', models.CharField(max_length=15)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('trade_name', models.CharField(blank=True, max_length=250)),
                ('address', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-is_primary', 'gstin'],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'gstin'), name='uq_client_gstin_tenant')],
            },
        ),
    ]
