# Generated by Django 5.2.1 on 2026-07-28 04:52

import core.db.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=core.db.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.UUIDField()),
                ('row_version', models.PositiveIntegerField(default=0)),
                ('vertical_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True)),
                ('owner_user_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'vertical_id', 'code'), name='uq_domain_code_vertical')],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=core.db.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.UUIDField()),
                ('row_version', models.PositiveIntegerField(default=0)),
                ('domain_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=180)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('default_owner_user_id', models.UUIDField(blank=True, null=True)),
                ('default_due_days', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'domain_id', 'code'), name='uq_service_code_domain')],
            },
        ),
        migrations.CreateModel(
            name='Vertical',
            fields=[
                ('id', models.UUIDField(default=core.db.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.UUIDField()),
                ('row_version', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True)),
                ('owner_user_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'code'), name='uq_vertical_code_tenant')],
            },
        ),
    ]
