from django.db import migrations, models

import core.db.uuid7


class Migration(migrations.Migration):
    dependencies = [
        ("ctx_configuration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceDocumentRequirementSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "created_by",
                    models.UUIDField(),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "updated_by",
                    models.UUIDField(),
                ),
                (
                    "row_version",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "service_id",
                    models.UUIDField(db_index=True),
                ),
                (
                    "name",
                    models.CharField(max_length=180),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(default=1),
                ),
                (
                    "effective_from",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        null=True,
                    ),
                ),
                (
                    "effective_until",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("RETIRED", "Retired"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True),
                ),
            ],
            options={
                "ordering": [
                    "service_id",
                    "-version_number",
                    "-effective_from",
                ],
            },
        ),
        migrations.CreateModel(
            name="ServiceDocumentRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.db.uuid7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(db_index=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "created_by",
                    models.UUIDField(),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "updated_by",
                    models.UUIDField(),
                ),
                (
                    "row_version",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "requirement_set_id",
                    models.UUIDField(db_index=True),
                ),
                (
                    "service_id",
                    models.UUIDField(db_index=True),
                ),
                (
                    "name",
                    models.CharField(max_length=200),
                ),
                (
                    "code",
                    models.CharField(max_length=60),
                ),
                (
                    "description",
                    models.TextField(blank=True),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GST", "GST"),
                            ("TDS", "TDS"),
                            ("INCOME_TAX", "Income Tax"),
                            ("ROC_MCA", "ROC / MCA"),
                            ("AUDIT", "Audit"),
                            ("ACCOUNTING", "Accounting"),
                            ("PAYROLL", "Payroll"),
                            ("BANKING", "Banking"),
                            ("REGISTRATION", "Registration"),
                            ("IDENTITY_KYC", "Identity / KYC"),
                            ("LEGAL", "Legal"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "mandatory",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=10),
                ),
                (
                    "financial_year_required",
                    models.BooleanField(default=False),
                ),
                (
                    "assessment_year_required",
                    models.BooleanField(default=False),
                ),
                (
                    "filing_period_required",
                    models.BooleanField(default=False),
                ),
                (
                    "expiry_applicable",
                    models.BooleanField(default=False),
                ),
                (
                    "expiry_reminder_days",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "requires_review",
                    models.BooleanField(default=True),
                ),
                (
                    "allow_multiple_versions",
                    models.BooleanField(default=True),
                ),
                (
                    "allow_multiple_files",
                    models.BooleanField(default=False),
                ),
                (
                    "allowed_extensions",
                    models.CharField(
                        blank=True,
                        help_text=(
                            "Comma-separated extensions, for example: "
                            "pdf,xlsx,xls,csv"
                        ),
                        max_length=250,
                    ),
                ),
                (
                    "maximum_file_size_mb",
                    models.PositiveIntegerField(default=15),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                    ),
                ),
            ],
            options={
                "ordering": [
                    "display_order",
                    "name",
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="servicedocumentrequirementset",
            constraint=models.UniqueConstraint(
                fields=[
                    "tenant_id",
                    "service_id",
                    "version_number",
                ],
                name="uq_docreqset_service_version",
            ),
        ),
        migrations.AddIndex(
            model_name="servicedocumentrequirementset",
            index=models.Index(
                fields=[
                    "tenant_id",
                    "service_id",
                    "status",
                ],
                name="idx_docreqset_service_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicedocumentrequirement",
            constraint=models.UniqueConstraint(
                fields=[
                    "tenant_id",
                    "requirement_set_id",
                    "code",
                ],
                name="uq_docrequirement_set_code",
            ),
        ),
        migrations.AddIndex(
            model_name="servicedocumentrequirement",
            index=models.Index(
                fields=[
                    "tenant_id",
                    "service_id",
                    "is_active",
                ],
                name="idx_docreq_service_active",
            ),
        ),
        migrations.AddIndex(
            model_name="servicedocumentrequirement",
            index=models.Index(
                fields=[
                    "tenant_id",
                    "requirement_set_id",
                    "display_order",
                ],
                name="idx_docrequirement_set_order",
            ),
        ),
    ]
