# Generated by Django 5.2.1 on 2026-08-06 19:37

import core.db.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctx_configuration', '0002_service_document_catalogue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOperationalField',
            fields=[
                ('id', models.UUIDField(default=core.db.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.UUIDField()),
                ('row_version', models.PositiveIntegerField(default=0)),
                ('service_id', models.UUIDField(db_index=True)),
                ('key', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=180)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('LONG_TEXT', 'Long text'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('BOOLEAN', 'Yes / No'), ('SELECT', 'Selection')], default='TEXT', max_length=20)),
                ('help_text', models.TextField(blank=True)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('required', models.BooleanField(db_index=True, default=False)),
                ('options', models.JSONField(blank=True, default=list)),
                ('display_order', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['display_order', 'label', 'id'],
                'indexes': [models.Index(fields=['tenant_id', 'service_id', 'is_active', 'display_order'], name='idx_service_operational_fields')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'service_id', 'key'), name='uq_service_operational_field_key')],
            },
        ),
    ]
