# Generated by Django 5.2.1 on 2026-08-09 01:47

import core.db.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctx_configuration', '0003_serviceoperationalfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceDeadlineRule',
            fields=[
                ('id', models.UUIDField(default=core.db.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.UUIDField()),
                ('row_version', models.PositiveIntegerField(default=0)),
                ('service_id', models.UUIDField(db_index=True)),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half yearly'), ('YEARLY', 'Yearly')], db_index=True, max_length=15)),
                ('due_day', models.PositiveSmallIntegerField()),
                ('due_month_offset', models.PositiveSmallIntegerField(default=0)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_until', models.DateField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['service_id', '-effective_from', '-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'service_id', 'frequency', 'is_active'], name='idx_deadline_rule_lookup')],
            },
        ),
    ]
