# Generated by Django 5.2.1 on 2026-08-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctx_configuration', '0004_compliancedeadlinerule'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancedeadlinerule',
            name='period_number',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
