# Generated by Django 5.2.1 on 2026-08-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctx_configuration', '0005_compliancedeadlinerule_period_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancedeadlinerule',
            name='period_start_month',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
