# Generated by Django 5.2.1 on 2026-08-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctx_configuration', '0006_compliancedeadlinerule_period_start_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancedeadlinerule',
            name='applicability',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
