# Generated by Django 5.2.1 on 2026-08-11 06:26

import core.db.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctx_configuration', '0007_compliancedeadlinerule_applicability'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProcessStep',
            fields=[
                ('id', models.UUIDField(default=core.db.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.UUIDField()),
                ('row_version', models.PositiveIntegerField(default=0)),
                ('service_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('display_order', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('service_id', 'display_order', 'name', 'id'),
                'indexes': [models.Index(fields=['tenant_id', 'service_id', 'is_active'], name='cfg_procstep_service_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'service_id', 'code'), name='uniq_service_process_step_code')],
            },
        ),
    ]
