# Generated by Django 5.2.1 on 2026-08-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctx_audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='ctx_audit_a_tenant__904740_idx',
            old_name='idx_audit_tenant_created',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='ctx_audit_a_tenant__6acb59_idx',
            old_name='idx_audit_entity',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='ctx_audit_a_tenant__bdac8a_idx',
            old_name='idx_audit_action',
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Record created'), ('UPDATE', 'Record updated'), ('DELETE', 'Record deleted'), ('OWNER_ASSIGNED', 'Owner assigned'), ('REVIEWER_ASSIGNED', 'Reviewer assigned'), ('STATUS_CHANGE', 'Status changed'), ('COMMENT_CREATED', 'Comment created'), ('DOCUMENT_REQUEST_CREATED', 'Document request created'), ('DOCUMENT_UPLOAD', 'Document uploaded'), ('ATTACHMENT_ACCEPTED', 'Attachment accepted'), ('ATTACHMENT_REJECTED', 'Attachment rejected'), ('EMPLOYEE_CREATED', 'Employee created'), ('EMPLOYEE_UPDATED', 'Employee updated'), ('EMPLOYEE_ACTIVATED', 'Employee activated'), ('EMPLOYEE_DEACTIVATED', 'Employee deactivated'), ('MANAGER_CHANGED', 'Manager changed'), ('ORG_STRUCTURE_CHANGED', 'Organisation structure changed'), ('EXPERTISE_CHANGED', 'Expertise changed'), ('CAPACITY_CHANGED', 'Capacity changed'), ('AVAILABILITY_OVERRIDE_CHANGED', 'Availability override changed'), ('LEAVE_CREATED', 'Leave created'), ('LEAVE_APPROVED', 'Leave approved'), ('LEAVE_REJECTED', 'Leave rejected'), ('LEAVE_CANCELLED', 'Leave cancelled'), ('ASSIGNMENT_EXECUTED', 'Assignment executed'), ('RECOMMENDATION_OVERRIDDEN', 'Recommendation overridden'), ('REVIEWER_HIERARCHY_CHANGED', 'Reviewer hierarchy changed'), ('MANAGER_OVERRIDE_USED', 'Manager override used')], db_index=True, max_length=30),
        ),
    ]
