# Generated by Django 5.2.1 on 2026-08-08 18:21

import core.db.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=core.db.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.UUIDField()),
                ('row_version', models.PositiveIntegerField(default=0)),
                ('recipient_principal_id', models.UUIDField(db_index=True)),
                ('notification_type', models.CharField(choices=[('WORK_ASSIGNED', 'Work assigned'), ('REVIEW_REQUESTED', 'Review requested'), ('REWORK_REQUESTED', 'Rework requested'), ('WORK_COMPLETED', 'Work completed')], db_index=True, max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('entity_type', models.CharField(blank=True, db_index=True, max_length=60)),
                ('entity_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'recipient_principal_id', 'read_at'], name='ctx_notific_tenant__87489a_idx'), models.Index(fields=['tenant_id', 'notification_type', 'created_at'], name='ctx_notific_tenant__18f4c3_idx')],
            },
        ),
    ]
