# Generated by Django 5.2.1 on 2026-07-28 04:52

import core.db.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=core.db.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.UUIDField()),
                ('row_version', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=180)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('employee_code', models.CharField(blank=True, max_length=40)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('PARTNER', 'Partner'), ('MANAGER', 'Manager'), ('STAFF', 'Staff'), ('READ_ONLY', 'Read only')], default='STAFF', max_length=20)),
                ('branch_id', models.UUIDField(blank=True, null=True)),
                ('team_id', models.UUIDField(blank=True, null=True)),
                ('expertise', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'email'), name='uq_employee_email_tenant')],
            },
        ),
    ]
