# Generated by Django 5.2.1 on 2026-08-06 11:42

import core.db.uuid7
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctx_identity', '0005_expertise_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.UUIDField(default=core.db.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(max_length=180)),
                ('password_hash', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('DISABLED', 'Disabled')], db_index=True, default='ACTIVE', max_length=12)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('failed_login_count', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='AuthenticationEvent',
            fields=[
                ('id', models.UUIDField(default=core.db.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('user_account_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('principal_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('session_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCEEDED', 'Login succeeded'), ('LOGIN_FAILED', 'Login failed'), ('LOGOUT', 'Logout'), ('SESSION_CREATED', 'Session created'), ('SESSION_REVOKED', 'Session revoked'), ('ACCESS_DENIED', 'Access denied'), ('PASSWORD_CHANGED', 'Password changed'), ('ACCOUNT_STATUS_CHANGED', 'Account status changed'), ('MEMBERSHIP_CHANGED', 'Membership changed')], db_index=True, max_length=32)),
                ('outcome', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('DENIED', 'Denied')], db_index=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['tenant_id', 'occurred_at'], name='ctx_identit_tenant__9975a0_idx'), models.Index(fields=['event_type', 'outcome'], name='ctx_identit_event_t_b3212e_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.UUIDField(default=core.db.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('user_account_id', models.UUIDField(db_index=True)),
                ('membership_id', models.UUIDField(db_index=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('principal_id', models.UUIDField(db_index=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent_hash', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_account_id', 'revoked_at'], name='ctx_identit_user_ac_11f560_idx'), models.Index(fields=['tenant_id', 'expires_at'], name='ctx_identit_tenant__9cd608_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProviderMembership',
            fields=[
                ('id', models.UUIDField(default=core.db.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.UUIDField()),
                ('row_version', models.PositiveIntegerField(default=0)),
                ('user_account_id', models.UUIDField(db_index=True)),
                ('employee_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('role', models.CharField(choices=[('PLATFORM_ADMIN', 'Platform administrator'), ('OPERATIONS_ADMIN', 'Operations administrator'), ('IMPLEMENTATION_CONSULTANT', 'Implementation consultant'), ('SUPPORT_CONSULTANT', 'Support consultant'), ('SECURITY_AUDITOR', 'Security auditor')], max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('ENDED', 'Ended')], db_index=True, default='ACTIVE', max_length=12)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['user_account_id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('tenant_id', 'user_account_id'), name='uq_active_provider_membership')],
            },
        ),
    ]
