# Generated by Django 5.2.1 on 2026-08-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctx_identity', '0006_useraccount_authenticationevent_authsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='invitation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='invited_by_principal_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
