# Generated by Django 5.2.1 on 2026-08-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctx_generation', '0002_task_template_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringworkprofile',
            name='operational_defaults',
            field=models.JSONField(blank=True, default=dict, help_text='Service-specific operational values copied into generated work items.'),
        ),
    ]
